const productTypes = {
  FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCT_RELATIVE_START: "FETCH_PRODUCT_RELATIVE_START",
  ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
  DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
  EDIT_PRODUCT_START: "EDIT_PRODUCT_START",
};
export default productTypes;
