const userTypes = {
  //User login
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  // User  signup
  USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILED: "USER_SIGNUP_FAILED",
  //User logout
  USER_LOGOUT: "USER_LOGOUT",
  //User clear data
  USER_CLEAR_DATA: "USER_CLEAR_DATA",
  //Current User
  SET_CURRENT_USER: "SET_CURRENT_USER",
};
export default userTypes;
