const categoryTypes = {
  ADD_NEW_CATEGORY: "ADD_NEW_CATEGORY",
  FETCH_ALL_CATEGORIES: "FETCH_ALL_CATEGORIES",
  EDIT_CATEGORY: "EDIT_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
};

export default categoryTypes;
