const orderTypes = {
  FETCH_ALL_ORDERS: "FETCH_ALL_ORDERS",
  FETCH_ORDER_HISTORY: "FETCH_ORDER_HISTORY",
  ADD_NEW_ORDER: "ADD_NEW_ORDER",
  DELETE_ORDER_START: "DELETE_ORDER_START",
  EDIT_ORDER_START: "EDIT_ORDER_START",
};
export default orderTypes;
